### ISSUE TITLE
Getting the error "Firebase: Firebase App named '[DEFAULT]' already exists"

### ISSUE THREAD

**Issue by Trilochan20** [antonybudianto/cra-universal#105]
So I successfully implemented this in my own existing react app. I switched from 'react-loadable' to 'lodable-components'. Installed everything required. It works fine. But sometimes server stops automatically while hot-reloading and I get this error message in terminal. 
`sswp> [DEFAULT]: Firebase: Firebase App named '[DEFAULT]' already exists (app/duplicate-app).
    at error (/home/trilochan/Desktop/ssr_test_2/node_modules/@firebase/app/dist/index.node.cjs.js:364:21)
    at Object.initializeApp (/home/trilochan/Desktop/ssr_test_2/node_modules/@firebase/app/dist/index.node.cjs.js:267:13)
    at eval (webpack:///./src/App.js?:73:15)
    at Object../src/App.js (/home/trilochan/Desktop/ssr_test_2/server-build/.hot/main.be93498ff83d44c322a0.hot-update.js:12:1)
    at __webpack_require__ (/home/trilochan/Desktop/ssr_test_2/server-build/bundle.js:683:30)
    at fn (/home/trilochan/Desktop/ssr_test_2/server-build/bundle.js:60:20)
    at eval (webpack:///./server/app.js?:46:21)
    at Object.hotApply [as apply] (/home/trilochan/Desktop/ssr_test_2/server-build/bundle.js:591:17)
    at eval (webpack:///./node_modules/start-server-webpack-plugin/dist/monitor-loader.js?./node_modules/start-server-webpack-plugin/dist/monitor-loader.js:14:27)
    at <anonymous>
sswp> Quitting process - will reload on next file change
sswp> script exited with code 222
sswp> Script did not load or failed HMR, not restarting`

In my App.js I've 

`import firebase from 'firebase/app';
import 'firebase/auth';
import 'firebase/database';
var config = {
    apiKey: "------------------------------------------------",
    authDomain: "------------------------------",
    databaseURL: "----------------------",
    projectId: "----------------------",
    storageBucket: "------------------------",
    messagingSenderId: "-------------------"
  };
  firebase.initializeApp(config);
export const database = firebase.database();
export const firebaseAuth = firebase.auth
export const ref = firebase.database().ref()`

Everytime It crashes I restart the server and It works fine for few moments. Then after some changes to the code sometimes it works sometimes I get that error message.

**Comment by Trilochan20** [comment]
If I again change something while the server existed, Then server refreshes and works fine.

**Comment by antonybudianto** [comment]
I need repo to reproduce this, otherwise sorry I cannot help :)

Also please post this to Stackoverflow

**Comment by antonybudianto** [comment]
I also used Firebase actually, and worked well, no problem so far
https://github.com/antonybudianto/antonybudianto-web

**Comment by antonybudianto** [comment]
Probably you need this check https://github.com/antonybudianto/antonybudianto-web/blob/master/src/App.js#L43
