### ISSUE TITLE
routes.map is not a function error on getInitialData

### ISSUE THREAD

**Issue by omerkocaaga** [antonybudianto/cra-universal#147]
When I am using @cra-express/router-prefetcher, I get this error.

```
/Users/omer/Sites/wp-react/node_modules/@cra-express/router-prefetcher/lib/index.js:11
  var matches = routes.map(function (route, index) {
                       ^

TypeError: routes.map is not a function
    at getInitialData (/Users/omer/Sites/wp-react/node_modules/@cra-express/router-prefetcher/lib/index.js:11:24)
    at handleUniversalRender (webpack:///./server/app.js?:42:95)
    at processRequest (/Users/omer/Sites/wp-react/node_modules/@cra-express/universal-loader/lib/universal.js:62:14)
    at IncomingMessage.<anonymous> (/Users/omer/Sites/wp-react/node_modules/@cra-express/universal-loader/lib/universal.js:27:7)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
sswp> script exited with code 1
sswp> running `node /Users/omer/Sites/wp-react/server-build/bundle.js --`
[Function: buildRoutes]
[HPM] Proxy created: /  ->  http://localhost:3000
Connected to CRA Client dev server
sswp> Handling Hot Module Reloading
sswp> Script loaded
CRA Server listening on port 3001!

```
Is it possible to using lodash map or something like that on this?

**Comment by antonybudianto** [comment]
hi, are you passing array to the 3rd arg of getInitialData?
>   return getInitialData(req, res, routes)

Judging from the error, it's not an array

**Comment by omerkocaaga** [comment]
yes, i am passing it but routes returned by a async function. Is it a problem?

**Comment by antonybudianto** [comment]
closing this, please reopen if you've any question
