### ISSUE TITLE
Missing loaders for images?

### ISSUE THREAD

**Issue by mbrochh** [antonybudianto/cra-universal#16]
When I'm trying to build my app for the server, I'm getting a lot of errors like these:

```
ERROR in ../src/static-artling/ImageModalNewsletter.jpg
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
```

I guess this is because in my components I'm doing imports like this:

```
import ImageModalNewsletterJpg from '../../../../static/ImageModalNewsletter.jpg'
```

Since these kinds of imports are supported by CRA, shouldn't they be supported by cra-universal as well?

**Comment by antonybudianto** [comment]
can you try to add image loader? If they don't use any hash or special transform, they should be compatible.
Not all file types are supported though, like svg.

**Comment by mbrochh** [comment]
Alright, somehow I didn't think that it was possible to change the webpack config for the server-side of things o_O

I added this:

```
      {
        exclude: [
          /\.html$/,
          /\.(js|jsx)$/,
          /\.css$/,
          /\.json$/,
          /\.bmp$/,
          /\.gif$/,
          /\.jpe?g$/,
          /\.png$/,
        ],
        loader: require.resolve('file-loader'),
        options: {
          name: '[name].[hash:8].[ext]',
        },
      },
      {
        test: [/\.bmp$/, /\.gif$/, /\.jpe?g$/, /\.png$/],
        loader: require.resolve('url-loader'),
        options: {
          limit: 10000,
          name: '[name].[hash:8].[ext]',
        },
      },
```

And now I am able to build the server bundle.

**Comment by joelaguero** [comment]
Just flagging that I ran into this issue with a fresh setup. @mbrochh solution unfortunately did not solve it for me and causes the following error: 
```
throw new Error("Module build failed: TypeError: Cannot read property 'context' of undefined\n    at Object.loader (/Users/joelaguero/Projects/progressivelabs/ib-landing/node_modules/file-loader/dist/index.js:34:48)\n    at Object.module.exports (/Users/joelaguero/Projects/progressivelabs/ib-landing/node_modules/url-loader/index.js:37:25)");
^

Error: Module build failed: TypeError: Cannot read property 'context' of undefined
    at Object.loader (/Users/joelaguero/Projects/progressivelabs/ib-landing/node_modules/file-loader/dist/index.js:34:48)
    at Object.module.exports (/Users/joelaguero/Projects/progressivelabs/ib-landing/node_modules/url-loader/index.js:37:25)
    at eval (webpack:///../src/logo.png?:1:7)
    at Object.../src/logo.png (/Users/joelaguero/Projects/progressivelabs/ib-landing/server/build/bundle.js:110:1)
    at __webpack_require__ (/Users/joelaguero/Projects/progressivelabs/ib-landing/server/build/bundle.js:23:30)
    at eval (webpack:///../src/App.js?:14:13)
    at Object.../src/App.js (/Users/joelaguero/Projects/progressivelabs/ib-landing/server/build/bundle.js:99:1)
    at __webpack_require__ (/Users/joelaguero/Projects/progressivelabs/ib-landing/server/build/bundle.js:23:30)
    at eval (webpack:///./src/app.js?:11:16)
    at Object../src/app.js (/Users/joelaguero/Projects/progressivelabs/ib-landing/server/build/bundle.js:122:1)
    at __webpack_require__ (/Users/joelaguero/Projects/progressivelabs/ib-landing/server/build/bundle.js:23:30)
    at eval (webpack:///./src/index.js?:4:11)
```

However, I was able to make things go by doing the following:
* Run `yarn add url-loader`
* Add the following to `server/webpack.config.js`:
```
      {
        test: /\.(png$|jpe?g$|gif$|bmp$)?$/,
        loaders: 'url-loader'
      }
```

**Comment by antonybudianto** [comment]
Yes, for now we can use `url-loader` although we get hydration warning on console.
Another alternative is using public path and store the images there (not using import syntax)

**Comment by antonybudianto** [comment]
You can disable the warning using:
https://reactjs.org/docs/dom-elements.html#suppresshydrationwarning
