### ISSUE TITLE
Problem Deploying to Firebase

### ISSUE THREAD

**Issue by gilbertl-shuffle** [antonybudianto/cra-universal#178]
**Describe the bug**
When deploying to firebase functions, I'm getting the following error:

Detailed stack trace: Error: Cannot find module '@cra-express/core'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.L.exports (/srv/crau-dist/server/bundle.js:1:1041)
    at N (/srv/crau-dist/server/bundle.js:1:172)
    at Module.<anonymous> (/srv/crau-dist/server/bundle.js:1:12272)
    at N (/srv/crau-dist/server/bundle.js:1:172)
    at Object.<anonymous> (/srv/crau-dist/server/bundle.js:1:12087)
    at N (/srv/crau-dist/server/bundle.js:1:172)

**To Reproduce**
1. initialize a firebase project with hosting and functions
2. npx create-react-app my-app
cd my-app
yarn i -D cra-universal
yarn add @cra-express/core
npx cra-universal start --both

3. npx cra-universal build

4. mv dist/ ../functions/crau-dist
5. add rewrite

{
        "source": "**",
        "function": "app"
      }
6. change functions/index.js

const functions = require('firebase-functions');
const app = require('./crau-dist/server/bundle');
exports.app = functions.https.onRequest(app);

7. firebase deploy

**Expected behavior**
deploy should succeed

**Other Notes**
eslint also fails, but I disabled it to run deploy

> functions@ lint /Users/gilbertl/Projects/test-cra/functions
> eslint .

Error: Cannot find module 'eslint-config-react-app'
Referenced from: /Users/gilbertl/Projects/test-cra/functions/crau-dist/package.json
    at ModuleResolver.resolve (/Users/gilbertl/Projects/test-cra/functions/node_modules/eslint/lib/util/module-resolver.js:72:19)
    at resolve (/Users/gilbertl/Projects/test-cra/functions/node_modules/eslint/lib/config/config-file.js:507:28)
    at load (/Users/gilbertl/Projects/test-cra/functions/node_modules/eslint/lib/config/config-file.js:579:26)
    at /Users/gilbertl/Projects/test-cra/functions/node_modules/eslint/lib/config/config-file.js:453:36
    at Array.reduceRight (<anonymous>)
    at applyExtends (/Users/gilbertl/Projects/test-cra/functions/node_modules/eslint/lib/config/config-file.js:431:26)
    at loadFromDisk (/Users/gilbertl/Projects/test-cra/functions/node_modules/eslint/lib/config/config-file.js:551:22)
    at Object.load (/Users/gilbertl/Projects/test-cra/functions/node_modules/eslint/lib/config/config-file.js:587:20)
    at Config.getLocalConfigHierarchy (/Users/gilbertl/Projects/test-cra/functions/node_modules/eslint/lib/config.js:240:44)
    at Config.getConfigHierarchy (/Users/gilbertl/Projects/test-cra/functions/node_modules/eslint/lib/config.js:192:43)

**Comment by antonybudianto** [comment]
Hi, I think you need to add `yarn add @cra-express/core` on your functions/package.json

**Comment by antonybudianto** [comment]
Feels free to reopen if still facing issue
