### ISSUE TITLE
Getting ECONNREFUSED when accessing dev server

### ISSUE THREAD

**Issue by zamirkhan** [antonybudianto/cra-universal#42]
Hello. Thank you for creating cra-universal. I'm trying to use it to add SSR to my CRA app. I followed the steps in the readme, along with one customization to overcome an error. My application references a common configuration file ('config.js') which lives outside of the CRA root, but exists inside the root via symlink. So to accommodate that, I added this to the webpack.config.js:

```
resolve: {
    symlinks: false,
    extensions: ['.js', '.jsx']
},
```

With this, I am able to run npm start from the ./server directory without errors:

```
MacBook-Pro:server zkhan$ npm start

create-react-app-server@1.0.0 start /Users/zkhan/Dev/nodejs/<removed>/client/server
cross-env NODE_ENV=development webpack --watch


Webpack is watching the files…

Hash: 94c69b74ab77d29f26c9
Version: webpack 4.6.0
Time: 6917ms
Built at: 04/30/2018 10:25:34 AM
    Asset     Size  Chunks             Chunk Names
bundle.js  6.6 MiB    main  [emitted]  main
Entrypoint main = bundle.js
...
<all the files>
...
[@cra-express/core] external "@cra-express/core" 42 bytes {main} [built]
[babel-runtime/regenerator] external "babel-runtime/regenerator" 42 bytes {main} [built]
[dotenv] external "dotenv" 42 bytes {main} [built]
[path] external "path" 42 bytes {main} [built]
[react] external "react" 42 bytes {main} [built]
    + 1209 hidden modules
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: build/bundle.js
[nodemon] starting `node build/bundle.js`
[HPM] Proxy created: /  ->  http://localhost:3000
Connected to CRA Client dev server
CRA Server listening on port 3001!
```

However, when I try to access localhost:3001 or localhost:3000, nothing renders ("The localhost page cannot be found") and the following error shows in the terminal:

```
connect ECONNREFUSED 127.0.0.1:3000
::1 - - [30/Apr/2018:14:25:51 +0000] "GET / HTTP/1.1" 404 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"
```

Any idea what I'm doing wrong? Thanks.

**Comment by antonybudianto** [comment]
Hi, 
Do you start the CRA client server? It's needed for development

**Comment by zamirkhan** [comment]
Thank you - I totally missed that. Now I get through to an actual (unrelated) error. By the way, my app is based on CRA for react v15. So I use 'render' instead of 'hydrate'. Is this package still expected to work?

Here is the error I get now:

```
events.js:163
      throw er; // Unhandled 'error' event
      ^

Invariant Violation: You should not use <Route> or withRouter() outside a <Router>
    at invariant (/Users/zkhan/Dev/nodejs/vidhug/client/server/node_modules/invariant/invariant.js:40:15)
    at Route.computeMatch (webpack:///../node_modules/react-router/es/Route.js?:71:53)
    at new Route (webpack:///../node_modules/react-router/es/Route.js?:46:20)
    at processChild (/Users/zkhan/Dev/nodejs/vidhug/client/server/node_modules/react-dom/cjs/react-dom-server.node.development.js:2082:14)
    at resolve (/Users/zkhan/Dev/nodejs/vidhug/client/server/node_modules/react-dom/cjs/react-dom-server.node.development.js:2048:5)
    at ReactDOMServerRenderer.render (/Users/zkhan/Dev/nodejs/vidhug/client/server/node_modules/react-dom/cjs/react-dom-server.node.development.js:2333:22)
    at ReactDOMServerRenderer.read (/Users/zkhan/Dev/nodejs/vidhug/client/server/node_modules/react-dom/cjs/react-dom-server.node.development.js:2307:19)
    at ReactMarkupReadableStream._read (/Users/zkhan/Dev/nodejs/vidhug/client/server/node_modules/react-dom/cjs/react-dom-server.node.development.js:2719:38)
    at ReactMarkupReadableStream.Readable.read (_stream_readable.js:350:10)
    at resume_ (_stream_readable.js:739:12)
```

**Comment by zamirkhan** [comment]
I got it sort-of working, using this: https://github.com/antonybudianto/cra-universal/wiki/Integrate-React-Router

Still having minor issues, but they're completely unrelated. Thanks again for creating this. Would still appreciate your input as to whether this will work with React V15.

**Comment by antonybudianto** [comment]
For React v15, it should work for some degree, using string renderer, since node stream API is only available at React v16.
